export const GET_VENUE_LIST = 'GET_VENUE_LIST';
export const SET_VENUE_LIST = 'SET_VENUE_LIST';
export const GET_VENUE_DETAIL = 'GET_VENUE_DETAIL';
export const SET_VENUE_DETAIL = 'SET_VENUE_DETAIL';
export const GET_REVIEWS = 'GET_REVIEWS';
export const SET_REVIEWS = 'SET_REVIEWS';

